In [10]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense


In [11]:
url = "https://raw.githubusercontent.com/ataislucky/Data-Science/main/dataset/emotion_train.txt"
data = pd.read_csv(url, sep=';')
data.columns = ["Text", "Emotions"]


In [12]:
print(data.head())
print()
print(data.count())

                                                Text Emotions
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness

Text        15999
Emotions    15999
dtype: int64


In [13]:
texts = data["Text"].tolist()
labels = data["Emotions"].tolist()

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Sample text data
textsTest = ["I love machine learning", "Deep learning is a subset of machine learning"]

# Create a tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the texts
tokenizer.fit_on_texts(textsTest)

# Display the word index
print("Word Index:", tokenizer.word_index)

# Display the word counts
print("Word Counts:", tokenizer.word_counts)

# Display the document count
print("Document Count:", tokenizer.document_count)

# Display the word sequences
sequences = tokenizer.texts_to_sequences(textsTest)
print("Sequences:", sequences)


Word Index: {'learning': 1, 'machine': 2, 'i': 3, 'love': 4, 'deep': 5, 'is': 6, 'a': 7, 'subset': 8, 'of': 9}
Word Counts: OrderedDict({'i': 1, 'love': 1, 'machine': 2, 'learning': 3, 'deep': 1, 'is': 1, 'a': 1, 'subset': 1, 'of': 1})
Document Count: 2
Sequences: [[3, 4, 2, 1], [5, 1, 6, 7, 8, 9, 2, 1]]


In [15]:
# Tokenize the text data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

In [16]:
sequences = tokenizer.texts_to_sequences(texts)
max_length = max([len(seq) for seq in sequences])
padded_sequences = pad_sequences(sequences, maxlen=max_length)

In [17]:
print(padded_sequences)

[[   0    0    0 ...    3   21 1254]
 [   0    0    0 ...    2  494  437]
 [   0    0    0 ...   29    5 3496]
 ...
 [   0    0    0 ...    3  101 1331]
 [   0    0    0 ...  339    8   42]
 [   0    0    0 ...   25 3585   12]]


In [18]:
# Encode the string labels to integers
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)
print(labels)

In [22]:
import tensorflow as tf
# one_hot_labels = keras.utils.to_categorical(labels)
one_hot_labels = tf.keras.utils.to_categorical(labels)
print(one_hot_labels)



[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [24]:
# Split the data into training and testing sets
xtrain, xtest, ytrain, ytest = train_test_split(padded_sequences, 
                                                one_hot_labels, 
                                                test_size=0.2)

In [37]:
print(len(tokenizer.word_index))
print(max_length)
print(one_hot_labels[0])

15212
66
[0. 0. 0. 0. 1. 0.]


In [38]:
# Define the model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, 
                    output_dim=128, input_length=max_length))
model.add(Flatten())
model.add(Dense(units=128, activation="relu"))
model.add(Dense(units=len(one_hot_labels[0]), activation="softmax"))

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(xtrain, ytrain, epochs=10, batch_size=32, validation_data=(xtest, ytest))

Epoch 1/10


c:\Users\prisa\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


400/400 ━━━━━━━━━━━━━━━━━━━━ 15s 35ms/step - accuracy: 0.4001 - loss: 1.5031 - val_accuracy: 0.7416 - val_loss: 0.8268
Epoch 2/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 13s 34ms/step - accuracy: 0.8845 - loss: 0.3868 - val_accuracy: 0.8138 - val_loss: 0.5542
Epoch 3/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9872 - loss: 0.0605 - val_accuracy: 0.8300 - val_loss: 0.5815
Epoch 4/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9940 - loss: 0.0273 - val_accuracy: 0.8153 - val_loss: 0.6456
Epoch 5/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9971 - loss: 0.0143 - val_accuracy: 0.8056 - val_loss: 0.7585
Epoch 6/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9962 - loss: 0.0159 - val_accuracy: 0.8256 - val_loss: 0.6533
Epoch 7/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9977 - loss: 0.0109 - val_accuracy: 0.8253 - val_loss: 0.6781
Epoch 8/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 34ms/step - accuracy: 0.9972 - loss: 0.0115 - val_accurac

In [39]:
#input_text from user
input_text = input("Please input sentence here : ")

# Preprocess the input text
input_sequence = tokenizer.texts_to_sequences([input_text])
padded_input_sequence = pad_sequences(input_sequence, maxlen=max_length)
prediction = model.predict(padded_input_sequence)
predicted_label = label_encoder.inverse_transform([np.argmax(prediction[0])])
print(predicted_label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
['love']
